version: "3"
services:
    postgres:
        image: "postgres:12"
        container_name: postgres
        restart: unless-stopped
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ConfTwitterBot
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        logging:
            driver: none

    nginx:
        container_name: nginx
        restart: unless-stopped
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80"
        depends_on:
            - backend
            - frontend

    backend:
        container_name: conf-twitter-bot-backend
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ConfTwitterBot
        volumes:
            - /app/node_modules
            - ./backend:/app
        depends_on:
            - postgres

    frontend:
        container_name: conf-twitter-bot-frontend
        stdin_open: true
        environment:
            - WDS_SOCKET_PORT=0
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app

volumes:
    postgres-data:
    pgadmin-data:
