version: '3'
services:
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
