version: "3"
services:
    postgres:
        image: postgres:12
        restart: always
        container_name: integration-tests-prisma
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: tests
