FROM ubuntu:18.04

# Install Node.js (Currently using the version recommended for docker, 14)
RUN apt-get update
RUN apt-get install --yes curl
RUN curl --silent --location https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install nodejs
RUN npm install -g yarn

WORKDIR /app
COPY ./package.json ./

RUN yarn install

# This command only works on Ubuntu (or any linux distro that uses apt-get instead of apk)
RUN yarn playwright install --with-deps chromium

COPY . .

CMD yarn prisma migrate deploy && yarn start
