name: Lint
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM packages
        run: npm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
