name: CI - Node.js

on: pull_request

jobs:
    install-packages:
        runs-on: ubuntu-latest
        steps:
            - name: Install Project Packages
            - uses: actions/checkout@v2
            - run: npm run install-packages

    postgres-db:
        name: Postgres
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: prisma
                    POSTGRES_PASSWORD: prisma
                    POSTGRES_DB: tests
                ports:
                    - 5433:5432

    lint:
        runs-on: ubuntu-latest
        needs: install-packages
        steps:
            - name: Linter Tests
            - uses: actions/checkout@v2
            - run: npx eslint . --ext .js,.jsx,.ts,.tsx

    backend-tests:
        runs-on: ubuntu-latest
        needs: [install-packages, postgres-db]
        working-directory: ./backend
        steps:
            - name: Code Tests
            - uses: actions/checkout@v2
            - run: npm run github-actions-test
        env:
            DATABASE_URL: 'postgresql://prisma:prisma@localhost:5433/tests'
