name: CI - Node.js

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Lint Packages
        run: npm install

      - name: Install Backend Packages
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Packages
        working-directory: ./frontend
        run: npm install

      - name: Lint Source Files
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
